<template>
  <Authenticated>
    <template v-slot:actions>
      <Button component="inertia-link" :href="$route('invoices.imports.edit', invoiceImport)">
        {{ __('Edit') }}
      </Button>
    </template>

    <CardWrapper class="mb-8">
      <CardPadding>
        <div class="text-lg leading-8">
          <p>{{ __('This is where you map the columns of your spreadsheet to individual fields for the invoice. You also have the ability to set an invoice field value manually and it will apply to every invoice generated by this import.') }}</p>
        </div>
      </CardPadding>
    </CardWrapper>

    <MapForm :headers="headers" v-model:invoice-form="form" :invoice-import="invoiceImport" />
  </Authenticated>
</template>

<script>
import { defineComponent, ref } from 'vue'
import Authenticated from '@/layouts/Authenticated'
import Button from '@/components/Button'
import MapForm from '@/pages/invoices/imports/MapForm'
import CardWrapper from '@/components/CardWrapper'
import CardPadding from '@/components/CardPadding'

export default defineComponent({
  components: {
    CardPadding,
    CardWrapper,
    MapForm,
    Button,
    Authenticated,
  },

  props: {
    invoiceImport: Object,
    headers: Array,
  },

  setup (props) {
    const form = ref({})

    return {
      form
    }
  }
})
</script>
