<template>
  <Authenticated>
    <template v-slot:actions>
      <div class="space-x-2">
        <Button size="sm" @click.prevent="showTemplates = true">
          {{ __('View templates') }}
        </Button>
        <Button component="inertia-link" :href="$route('invoices.imports.edit', invoiceImport)" size="sm">
          {{ __('Edit') }}
        </Button>
      </div>
    </template>

    <CardWrapper class="mb-8">
      <CardPadding>
        <div class="leading-6">
          <p>{{ __('This is where you map the columns of your spreadsheet to individual fields for the invoice. You also have the ability to set an invoice field value manually and it will apply to every invoice generated by this import.') }}</p>
        </div>
      </CardPadding>
    </CardWrapper>

    <MapForm
      v-model:invoice-form="form"
      :headers="headers"
      :invoice-import="invoiceImport"
      :invoice-template="invoiceTemplate"
      :errors="errors"
    />
  </Authenticated>

  <InvoiceTemplatesModal
    v-if="showTemplates"
    @use="useTemplate"
    @close="showTemplates = false"
    :invoice="form"
    :for-import="true"
  />
</template>

<script>
import { defineComponent, ref } from 'vue'
import Authenticated from '@/layouts/Authenticated'
import Button from '@/components/Button'
import MapForm from '@/pages/invoices/imports/MapForm'
import CardWrapper from '@/components/CardWrapper'
import CardPadding from '@/components/CardPadding'
import InvoiceTemplatesModal from '@/components/modals/InvoiceTemplatesModal'
import PageProps from '@/mixins/PageProps'

export default defineComponent({
  mixins: [PageProps],
  components: {
    InvoiceTemplatesModal,
    CardPadding,
    CardWrapper,
    MapForm,
    Button,
    Authenticated,
  },

  props: {
    invoiceImport: Object,
    headers: Array,
  },

  setup (props) {
    const showTemplates = ref(false)
    const invoiceTemplate = ref({})
    const form = ref({})
    const useTemplate = template => {
      invoiceTemplate.value = template.template
    }

    return {
      showTemplates,
      invoiceTemplate,
      useTemplate,
      form,
    }
  }
})
</script>
